version: '3'
services:

  hydra:
    image: linuxserver/hydra:latest
    restart: "unless-stopped"
    ports:
    - "5075:5075"
    volumes:
    - /home/james/Docker/NZBHydra/Config:/config
    - /home/james/Docker/NZBHydra/Downloads:/downloads
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  hass:
    image: homeassistant/home-assistant:latest
    restart: "unless-stopped"
    volumes:
    - /home/james/Docker/HomeAssistant/Config:/config
    - /etc/localtime:/etc/localtime

  nzbget:
    image: linuxserver/nzbget:latest
    restart: "unless-stopped"
    ports:
    - "6789:6789"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    volumes:
    - /home/james/Docker/NZBGet/Config:/config
    - /home/james/Docker/NZBGet/Downloads:/downloads
