version: '3'
services:

  radarr:
    image: linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    restart: "unless-stopped"
    ports:
    - "7878:7878"
    volumes:
    - ${DOCKER_DATA}/Radarr/Config:/config
    - ${DOCKER_DATA}/NZBGet/Downloads:/downloads
    - /mnt/34D26DEED26DB4B0/Video:/movies
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  sonarr:
    image: linuxserver/sonarr:latest
    hostname: sonarr
    container_name: sonarr
    restart: "unless-stopped"
    ports:
    - "8989:8989"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    volumes:
    - ${DOCKER_DATA}/Sonarr/Config:/config
    - ${DOCKER_DATA}/NZBGet/Downloads:/downloads
    - /mnt/34D26DEED26DB4B0/Television:/tv
    - /etc/localtime:/etc/localtime:ro

  hydra:
    image: linuxserver/hydra:latest
    hostname: hydra
    container_name: hydra
    restart: "unless-stopped"
    ports:
    - "5075:5075"
    volumes:
    - ${DOCKER_DATA}/NZBHydra/Config:/config
    - ${DOCKER_DATA}/NZBHydra/Downloads:/downloads
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  nzbget:
    image: linuxserver/nzbget:latest
    hostname: nzbget
    container_name: nzbget
    restart: "unless-stopped"
    ports:
    - "6789:6789"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    volumes:
    - ${DOCKER_DATA}/NZBGet/Config:/config
    - ${DOCKER_DATA}/NZBGet/Downloads:/downloads

  tautulli:
    image: linuxserver/tautulli:latest
    hostname: tautulli
    container_name: tautulli
    restart: "unless-stopped"
    ports:
    - "8181:8181"
    volumes:
    - ${DOCKER_DATA}/Tautulli/Config:/config
    - ${DOCKER_DATA}/Tautulli/Logs:/logs
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  plex:
    image: linuxserver/plex:latest
    hostname: plex
    container_name: plex
    restart: "unless-stopped"
    ports:
    - "32400:32400"
    - "32400:32400/udp"
    - "32469:32469"
    - "32469:32469/udp"
    - "5353:5353/udp"
    - "1900:1900/udp"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    - VERSION=latest
    volumes:
    - ${DOCKER_DATA}/Plex/Transcoding:/transcode
    - /mnt/34D26DEED26DB4B0/Docker/Plex/Config:/config
    - /mnt/34D26DEED26DB4B0/Television:/data/tvshows
    - /mnt/34D26DEED26DB4B0/Video:/data/movies

  watchtower:
    image: v2tec/watchtower:latest
    hostname: watchtower
    container_name: watchtower
    restart: "unless-stopped"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 1 12 * * *" --cleanup
    environment:
    - WATCHTOWER_NOTIFICATIONS=slack
    - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_WEBHOOK}

  portainer:
    image: portainer/portainer:latest
    hostname: portainer
    container_name: portainer
    restart: "unless-stopped"
    ports:
    - "9000:9000"
    volumes:
    - ${DOCKER_DATA}/Portainer/Data:/data
    - /var/run/docker.sock:/var/run/docker.sock

#  ombi:
#    image: linuxserver/ombi:latest
#    hostname: ombi
#    container_name: ombi
#    restart: "unless-stopped"
#    ports:
#    - "3579:3579"
#    volumes:
#    - ${DOCKER_DATA}/Ombi/Config:/config
#    environment:
#    - PGID=1000
#    - TZ=Europe/London

#  phlex:
#    image: digitalhigh/phlex:latest
#    hostname: phlex
#    container_name: phlex
#    restart: "unless-stopped"
#    volumes:
#    - ${DOCKER_DATA}/Phlex/Config:/config
#    environment:
#    - PGID=1000
#    - PUID=1000
#    - TZ=Europe/London

#  nfs:
#    image: itsthenetwork/nfs-server-alpine:latest
#    hostname: nfs
#    container_name: nfs
#    restart: "unless-stopped"
#    ports:
#    - "2049:2049"
#    volumes:
#    - /data1/:/nfsshare
#    environment:
#    - SHARED_DIRECTORY=/mnt/34D26DEED26DB4B0
#    - READ_ONLY=true

#  hass:
#    image: homeassistant/home-assistant:latest
#    hostname: hass
#    container_name: hass
#    restart: "unless-stopped"
#    volumes:
#    - ${DOCKER_DATA}/HomeAssistant/Config:/config
#    - /etc/localtime:/etc/localtime:ro
