version: '3'
services:

  hydra:
    image: linuxserver/hydra:latest
    restart: "unless-stopped"
    ports:
    - "5075:5075"
    volumes:
    - /home/james/Docker/NZBHydra/Config:/config
    - /home/james/Docker/NZBHydra/Downloads:/downloads
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  hass:
    image: homeassistant/home-assistant:latest
    restart: "unless-stopped"
    volumes:
    - /home/james/Docker/HomeAssistant/Config:/config
    - /etc/localtime:/etc/localtime

  nzbget:
    image: linuxserver/nzbget:latest
    restart: "unless-stopped"
    ports:
    - "6789:6789"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    volumes:
    - /home/james/Docker/NZBGet/Config:/config
    - /home/james/Docker/NZBGet/Downloads:/downloads

  ombi:
    image: linuxserver/ombi:latest
    restart: "unless-stopped"
    ports:
    - "3579:3579"
    volumes:
    - /home/james/Docker/Ombi/Config:/config
    environment:
    - PGID=1000
    - TZ=Europe/London

  phlex:
    image: digitalhigh/phlex:latest
    restart: "unless-stopped"
    volumes:
    - /home/james/Docker/Phlex/Config:/config
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  plex:
    image: linuxserver/plex:latest
    restart: "unless-stopped"
    ports:
    - "32400:32400"
    - "32400:32400/udp"
    - "32469:32469"
    - "32469:32469/udp"
    - "5353:5353/udp"
    - "1900:1900/udp"
    environment:
    - VERSION=latest
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    volumes:
    - /mnt/34D26DEED26DB4B0/Docker/Plex/Config:/config
    - /mnt/34D26DEED26DB4B0/Television:/data/tvshows
    - /mnt/34D26DEED26DB4B0/Video:/data/movies
    - /home/james/Docker/Plex/Transcoding:/transcode

  portainer:
    restart: "unless-stopped"
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/james/Docker/Portainer/Data:/data
