version: '3'
services:

  radarr:
  image: linuxserver/radarr:latest
  restart: "unless-stopped"
  ports:
  - "7878:7878"
  volumes:
  - /home/james/Docker/Radarr/Config:/config
  - /home/james/Docker/NZBGet/Downloads:/downloads
  - /mnt/34D26DEED26DB4B0/Video:/movies
  - /etc/localtime:/etc/localtime:ro
  environment:
  - TZ=Europe/London
  - PUID=1000
  - PGID=1000

  sonarr:
    image: linuxserver/sonarr:latest
    restart: "unless-stopped"
    ports:
    - "8989:8989"
    environment:
    - TZ=Europe/London
    - PUID=1000
    - PGID=1000
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/james/Docker/Sonarr/Config:/config
    - /mnt/34D26DEED26DB4B0/Television:/tv
    - /home/james/Docker/NZBGet/Downloads:/downloads

  hydra:
    image: linuxserver/hydra:latest
    restart: "unless-stopped"
    ports:
    - "5075:5075"
    volumes:
    - /home/james/Docker/NZBHydra/Config:/config
    - /home/james/Docker/NZBHydra/Downloads:/downloads
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London

  nzbget:
    image: linuxserver/nzbget:latest
    restart: "unless-stopped"
    ports:
    - "6789:6789"
    environment:
    - PGID=1000
    - PUID=1000
    - TZ=Europe/London
    volumes:
    - /home/james/Docker/NZBGet/Config:/config
    - /home/james/Docker/NZBGet/Downloads:/downloads

  tautulli:
    image: linuxserver/tautulli:latest
    restart: "unless-stopped"
    ports:
    - "8181:8181"
    volumes:
    - /home/james/Docker/Tautulli/Config:/config
    - /home/james/Docker/Tautulli/Logs:/logs
    environment:
    - TZ=Europe/London
    - PUID=1000
    - PGID=1000

  plex:
    image: linuxserver/plex:latest
    restart: "unless-stopped"
    ports:
    - "32400:32400"
    - "32400:32400/udp"
    - "32469:32469"
    - "32469:32469/udp"
    - "5353:5353/udp"
    - "1900:1900/udp"
    environment:
    - VERSION=latest
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    volumes:
    - /mnt/34D26DEED26DB4B0/Docker/Plex/Config:/config
    - /mnt/34D26DEED26DB4B0/Television:/data/tvshows
    - /mnt/34D26DEED26DB4B0/Video:/data/movies
    - /home/james/Docker/Plex/Transcoding:/transcode

  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: v2tec/watchtower:0.3
    restart: "unless-stopped"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 1 12 * * *" --cleanup
    environment:
    - WATCHTOWER_NOTIFICATIONS=slack
    - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=xx # todo

#  ombi:
#    image: linuxserver/ombi:latest
#    restart: "unless-stopped"
#    ports:
#    - "3579:3579"
#    volumes:
#    - /home/james/Docker/Ombi/Config:/config
#    environment:
#    - PGID=1000
#    - TZ=Europe/London

#  phlex:
#    image: digitalhigh/phlex:latest
#    restart: "unless-stopped"
#    volumes:
#    - /home/james/Docker/Phlex/Config:/config
#    environment:
#    - PGID=1000
#    - PUID=1000
#    - TZ=Europe/London

#  portainer:
#    image: portainer/portainer:latest
#    restart: "unless-stopped"
#    ports:
#    - "9000:9000"
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    - /home/james/Docker/Portainer/Data:/data

#  nfs:
#    image: itsthenetwork/nfs-server-alpine:latest
#    restart: "unless-stopped"
#    ports:
#    - "2049:2049"
#    volumes:
#    - /data1/:/nfsshare
#    environment:
#    - SHARED_DIRECTORY=/mnt/34D26DEED26DB4B0
#    - READ_ONLY=true

#  hass:
#    image: homeassistant/home-assistant:latest
#    restart: "unless-stopped"
#    volumes:
#    - /home/james/Docker/HomeAssistant/Config:/config
#    - /etc/localtime:/etc/localtime
